name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    uses: i-dream-of-ai/mcp-creator/.github/workflows/deploy-mcp-server.yml@main
    with:
      server-name: mcp-email-aws-ses
      environment: production
      notify-webhook: true
    secrets: inherit